### PR TITLE
update(fdi-metadata-search): deprecated fdi-metadata-search-searchapi

### PR DESCRIPTION
**Pull request by SystemFiles**
Moved `fdi-metadata-search-searchapi` from stable to deprecated

### CODE REVIEW

**Comment by SajidDeo** [comment]
LGTM

**Comment by SajidDeo** [comment]
LGTM unfortunatey I don't have approve access :(

**Review by SajidDeo — APPROVED** [review]
LGTM

**Review by mohameddahrouj — APPROVED** [review]

**Comment by SystemFiles** [comment]
Closing. Client will have to decide what they want to do with chart

**Pull request closed without merging**
