### PR TITLE
fix:(ckan) readiness liveness command instead of httpGet

### PR DESCRIPTION
**Pull request by Locutus66**
- Added readiness/liveness probe as a command in place of the problematic httpGet call

### CODE REVIEW

**Comment by blairdrummond** [comment]
Are you sure this works? I think `cat folder` breaks.

Just comment out the whole probes

**Comment by blairdrummond** [comment]
What did it return? Can you do

```
cat /srv/app; echo $?
```

**Comment by Locutus66** [comment]
ckan@ckan-694cc84bd7-c2kcp:/$ cat /srv/app
cat: /srv/app: Is a directory

**Comment by blairdrummond** [comment]
That is an error, so the probe will fail

**Comment by Locutus66** [comment]
> That is an error, so the probe will fail

how, why?

**Comment by blairdrummond** [comment]
Screenshot from 2021-07-28 14-56-11

You have to check the 0/1 exit status using `echo $?` or using an if statement.

**Pull request merged**
