### PR TITLE
FDI - SDMX Helm Chart Updates

### PR DESCRIPTION
**Pull request by traizenne**
updates to the fdi-dotstatsuite charts.
The updates to the charts and templates make this deployable for each instance needed. 
The charts will need to be set up in Octopus and ArgoCD

### CODE REVIEW

**Comment by sylus** [comment]
Can we not delete the old dotstatsuite chart and instead move to deprecated?

I sometimes use this chart as I wrote it to test things when am asked to assist with SDMX.

**Comment by traizenne** [comment]
Sure.  We can deprecate it.  The updated chart is essentially going back to a similar version of that chart anyways.  
Do you need me to submit another PR to move it?

**Comment by sylus** [comment]
Hey @traizenne yeah can this P.R. be updated to only touch fdi-dotstatsuite? 

I will move dotstatsuite myself to deprecated.

Sorry for the pain but me and @zachomedia spent time on the dotstatsuite and if ever there is a problem and you ask for our help we might use that as a base since mostly familiar with it.

Let me know!

**Comment by traizenne** [comment]
@sylus Sounds good!  Thanks again.

**Pull request closed without merging**
