### PR TITLE
update: fdi-eck 0.3.0

### PR DESCRIPTION
**Pull request by GoodTown**
added elastic.yaml, kibana.yaml, elastic_ingress.yaml, kibana_ingress.yaml
removed password from values.yaml
incremented chart to 0.3.0

### CODE REVIEW

**Comment by GoodTown** [comment]
made some minor fixes to dotstatsuite-de-dv and dotstatsuite-dlm, tested changes locally.

**Comment by chuckbelisle** [comment]
@rohank07 and @vexingly , could one or both of you review this PR for Philippe? https://statcan-aaw.slack.com/archives/C02FH2GD70X/p1670956645654769

**Review by rohank07 — APPROVED** [review]
Lgtm

**Comment by vexingly** [comment]
The namespace `fdi` does not exist and will need to be updated...

The existing elasticseach / kibana and related resources for fdi (and other projects) can be found in the _aaw-argocd-manifests_ repository, specifcally https://github.com/StatCan/aaw-argocd-manifests/tree/aaw-dev-cc-00/org-fdi-system ... so I'm not sure if recreating them via this helm chart will work well with argocd managing the existing deployment.

You can view the existing FDI deployments https://org-fdi-system-argocd.aaw-dev.cloud.statcan.ca/applications / https://org-fdi-system-argocd.aaw.cloud.statcan.ca/applications

**Comment by GoodTown** [comment]
You are correct we shouldnt have the fdi namespace hardcoded in the ingress and services that will need to change. 

We also have deployments in cloud main, the fdi namespace exists there. We could continue using the existing eck portal for aaw but we need this helm chart deployment for cloud main. We could find a way to re-use this helm chart in aaw and aaw-dev by setting the namespace variable in argo-cd.

**Pull request merged**
